USE [LOL_WILD_RIFT_DB]
GO
/****** Object:  Table [dbo].[RECOMMENDED_LANE]    Script Date: 19-Dec-20 1:12:50 PM ******/
DROP TABLE [dbo].[RECOMMENDED_LANE]
GO
/****** Object:  Table [dbo].[RECOMMENDED_LANE]    Script Date: 19-Dec-20 1:12:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECOMMENDED_LANE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LANE] [varchar](50) NULL
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[RECOMMENDED_LANE] ON 

INSERT [dbo].[RECOMMENDED_LANE] ([ID], [LANE]) VALUES (1, N'BARON LANE')
INSERT [dbo].[RECOMMENDED_LANE] ([ID], [LANE]) VALUES (2, N'MID LANE')
INSERT [dbo].[RECOMMENDED_LANE] ([ID], [LANE]) VALUES (3, N'DRAGON LANE')
INSERT [dbo].[RECOMMENDED_LANE] ([ID], [LANE]) VALUES (4, N'JUNGLE LANE')
SET IDENTITY_INSERT [dbo].[RECOMMENDED_LANE] OFF
