USE [LOL_WILD_RIFT_DB]
GO
/****** Object:  StoredProcedure [dbo].[CHAMPIONS.SP_UPDATE_STATS]    Script Date: 19-Dec-20 1:12:50 PM ******/
DROP PROCEDURE [dbo].[CHAMPIONS.SP_UPDATE_STATS]
GO
/****** Object:  StoredProcedure [dbo].[CHAMPIONS.SP_UPDATE_STATS]    Script Date: 19-Dec-20 1:12:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Sophon.Ju
-- Create date: 19/12/2020
-- Description:	Update stats
-- =============================================
CREATE PROCEDURE [dbo].[CHAMPIONS.SP_UPDATE_STATS]
	@ID	INT,
	@DAMAGE INT,
	@TOUGHNESS INT,
	@UTILITY INT,
	@DIFFICULITY INT
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @RESULT BIT
	BEGIN TRY
		IF EXISTS(SELECT TOP 1 [ID] FROM CHAMPIONS WHERE ID = @ID)
		BEGIN
			UPDATE CHAMPIONS SET 
			STATS_DAMAGE	= ISNULL(@DAMAGE, STATS_DAMAGE),
			STATS_TOUGHNESS = ISNULL(@TOUGHNESS, STATS_TOUGHNESS),
			STATS_UTILITY	= ISNULL(@UTILITY, STATS_UTILITY),
			STATS_DIFFICULITY	= ISNULL(@DIFFICULITY, STATS_DIFFICULITY)
			WHERE ID = @ID

			SET @RESULT = 1
		END
		ELSE SET @RESULT = 0
	END TRY
	BEGIN CATCH
		SET @RESULT = 0
	END CATCH
	SELECT @RESULT AS RESULT
END
GO
