USE [master]
GO
/****** Object:  Database [LOL_WILD_RIFT_DB]    Script Date: 19-Dec-20 1:12:50 PM ******/
DROP DATABASE [LOL_WILD_RIFT_DB]
GO
/****** Object:  Database [LOL_WILD_RIFT_DB]    Script Date: 19-Dec-20 1:12:50 PM ******/
CREATE DATABASE [LOL_WILD_RIFT_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LOL_WILD_RIFT_DB', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\LOL_WILD_RIFT_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LOL_WILD_RIFT_DB_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\LOL_WILD_RIFT_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LOL_WILD_RIFT_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET  MULTI_USER 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET QUERY_STORE = OFF
GO
ALTER DATABASE [LOL_WILD_RIFT_DB] SET  READ_WRITE 
GO
